ciao

diff --git a/autogitconfigure b/autogitconfigure
--- a/autogitconfigure
+++ b/autogitconfigure
@@ -3,7 +3,8 @@
 #
 # author stefano fattore
 #
-# version BETA 0.3.2
+# version BETA 0.3.3
+
 
 FULL="NO"
 DEPENDECIES="NO"
@@ -86,9 +87,7 @@ fi
 if [ $COUNT -eq 0 ]; then
     echo "[ERR] => No args detected, use --help for tips"
     exit -1
-fi
-
-if [ $# -gt 0 ]; then 
+elif [ $COUNT -gt 0 ]; then 
     signature
 fi
 
@@ -127,43 +126,62 @@ user_data(){
 
 dependencies(){
     echo "==============================================="
-    echo "          Installing dependencies"
+    echo "           Checking dependencies"
     echo "==============================================="
     echo
 
-    PACKAGE="expect openssl"
-    DEB_PACKAGE_NAME="expect openssl"
-    FEDORA_PACKAGE_NAME="expect openssl"
-    ARCH_PACKAGE_NAME="expect openssl"
+    PACKAGE=""
+    PACKAGE1=""
+    PACKAGE2=""
 
-    echo "Installing packages $PACKAGE on $(( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1)"
-    echo "Press [y/n] to proceed"
-    read response
+    if ! type "expect" &> /dev/null; then
+        PACKAGE1="expect"
+    fi
+    if ! type "openssl" &> /dev/null; then
+        PACKAGE2="openssl"
+    fi
+    PACKAGE="${PACKAGE1} ${PACKAGE2}"
 
-    if [ $response == "y" ] || [ $response == "Y" ]; then 
-        if [ -x "$(command -v apt)" ]; then 
-            sudo apt update
-            sudo apt install -y $DEB_PACKAGE_NAME
-        elif [ -x "$(command -v pacman)" ]; then 
-            sudo pacman -S $ARCH_PACKAGE_NAME
-        elif [ -x "$(command -v dnf)" ]; then
-            sudo dnf install $FEDORA_PACKAGE_NAME
-        elif [ -x "$(command -v yum)" ]; then
-            sudo yum update
-            sudo yum install $PACKAGE
-        elif [ -x "$(command -v xbps)" ]; then
-            sudo xbps-install -Su $PACKAGE
-        else 
-            echo "OS NOT DETECTED, couldn't install package $PACKAGE"
-            exit 1;
-        fi
-
+    if [[ $PACKAGE == " " ]]
+    then
+        echo "==============================================="
+        echo "       All dependencies are satisfied"
+        echo "==============================================="
         echo
-        echo "==============================================="
-        echo "Package $PACKAGE installed successfully"
-        echo "==============================================="
     else
-        echo "Dependencies installation aborted, quitting"
+        echo "==============================================="
+        echo "           Installing dependencies"
+        echo "==============================================="
+        echo
+        echo "Installing packages $PACKAGE on $(( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1)"
+        echo "Press [y/n] to proceed"
+        read response
+
+        if [ $response == "y" ] || [ $response == "Y" ]; then 
+            if [ -x "$(command -v apt)" ]; then 
+                sudo apt update
+                sudo apt install -y $PACKAGE
+            elif [ -x "$(command -v pacman)" ]; then 
+                sudo pacman -S $PACKAGE
+            elif [ -x "$(command -v dnf)" ]; then
+                sudo dnf install $PACKAGE
+            elif [ -x "$(command -v yum)" ]; then
+                sudo yum update
+                sudo yum install $PACKAGE
+            elif [ -x "$(command -v xbps)" ]; then
+                sudo xbps-install -Su $PACKAGE
+            else 
+                echo "OS NOT DETECTED, couldn't install package $PACKAGE"
+                exit 1;
+            fi
+
+            echo
+            echo "==============================================="
+            echo "Package $PACKAGE installed successfully"
+            echo "==============================================="
+        else
+            echo "Dependencies installation aborted, quitting"
+        fi
     fi
 }
 
