BETA 0.2

diff --git a/config b/config
--- a/config
+++ b/config
@@ -3,11 +3,13 @@
 #
 # author stefano fattore
 #
-# version BETA 0.1.3
+# version BETA 0.2
 
 DEPENDECIES=0
 GITDATA=0
 SSHDATA=0
+SSHCFG=""
+SILENT=0
 COUNT=0
 
 helper(){
@@ -21,6 +23,9 @@ helper(){
     echo
     echo "  -d|--deps"
     echo "      check for dep and install them"
+    echo
+    echo "  --silent"
+    echo "      no echos"
     echo
     echo "  -h|--help"
     echo "      print user friendly helper"
@@ -44,8 +49,18 @@ for i in "$@"; do
         SSHDATA=1
         shift 
         ;;
+    -sr=*|--ssh-replace=*)
+        SSHCFG="${i#*=}"
+        SSHDATA=1
+        SILENT=1
+        shift 
+        ;;
     -h|--help)
         helper
+        shift 
+        ;;
+    --silent)
+        SILENT=1
         shift 
         ;;
     -*|--*)
@@ -103,11 +118,13 @@ fi
 
 
 git_data(){
-    echo
-    echo "==============================================="
-    echo "          Set up your git credentials"
-    echo "==============================================="
-    echo    
+    if [ $SILENT -eq 0   ]; then
+        echo
+        echo "==============================================="
+        echo "          Set up your git credentials"
+        echo "==============================================="
+        echo  
+    fi  
 
     echo "> Set username: "
     read uname
@@ -131,10 +148,14 @@ git_data(){
         rm -f ${basedir}/git/ss
     fi
 
-    echo "Created ${basedir}/git/conf file.."
+    if [ $SILENT -eq 0 ]; then
+        echo "Created ${basedir}/git/conf file.."
+    fi
     touch ${basedir}/git/conf/encr
 
-    echo "Created ${basedir}/ss file.."
+    if [ $SILENT -eq 0 ]; then
+        echo "Created ${basedir}/ss file.."
+    fi
     touch ${basedir}/git/ss
 
     head -c 256 /dev/random | base64 > ${basedir}/git/conf/encr  # gen rand pass
@@ -147,24 +168,65 @@ git_data(){
     chmod 0400 ${basedir}/git/ss                                # set minimal privs
 }
 
+function valid_ip()
+{
+    local  IPA1=$1
+    local  stat=0
+
+    if [[ $IPA1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
+    then
+        OIFS=$IFS
+        IFS='.'
+        ip=($IPA1)
+        IFS=$OIFS
+
+        if [[ ${ip[0]} -le 255 ]] && [[ ${ip[1]} -le 255 ]] && [[ ${ip[2]} -le 255 ]] && [[ ${ip[3]} -le 255 ]];
+        then
+            stat=1
+        fi
+    fi
+    return $stat
+}
+
 ssh_data(){
-    echo
-    echo "==============================================="
-    echo "          Set up your ssh credentials"
-    echo "==============================================="
-    echo    
+    if [ $SILENT -eq 0 ]; then
+        echo
+        echo "==============================================="
+        echo "          Set up your ssh credentials"
+        echo "==============================================="
+        echo  
+    fi  
 
     echo "> Set username: "
     read uname
 
-    echo "> Set host:"
+    echo "> Set ip:"
     read host
+
+    valid_ip $host
+    res=$?
+
+    while [[ $res -eq 0 ]]
+    do
+        echo "Invalid ip"
+        echo "> Set new ip:"
+        read host
+
+        valid_ip $host
+        res=$?
+    done
 
     echo "> Set password: (silent)"
     read -s passwd
 
     if [[ ! -d "${basedir}/ssh/${uname}@${host}" ]]
     then
+        if [ $SSHCFG != "" ]; then
+            if [[ -d "${basedir}/ssh/${SSHCFG}" ]]
+            then
+                rm -rf ${basedir}/ssh/${SSHCFG}
+            fi
+        fi
         echo "Created ${basedir}/ssh/${uname}@${host} folder.."
         mkdir ${basedir}/ssh/${uname}@${host}
     else
@@ -179,10 +241,14 @@ ssh_data(){
         mkdir ${basedir}/ssh/${uname}@${host}/conf
     fi
 
-    echo "Created ${basedir}/ssh/${uname}@${host}/conf/encr file.."
+    if [ $SILENT -eq 0 ]; then
+        echo "Created ${basedir}/ssh/${uname}@${host}/conf/encr file.."
+    fi
     touch ${basedir}/ssh/${uname}@${host}/conf/encr
 
-    echo "Created ${basedir}/ssh/${uname}@${host}/ss file.."
+    if [ $SILENT -eq 0 ]; then
+        echo "Created ${basedir}/ssh/${uname}@${host}/ss file.."
+    fi
     touch ${basedir}/ssh/${uname}@${host}/ss
 
     head -c 256 /dev/random | base64 > ${basedir}/ssh/${uname}@${host}/conf/encr  # gen rand pass
