BETA 0.1.3

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@
 #
 # author stefano fattore
 #
-# version BETA 0.1.2
+# version BETA 0.1.3
 
 if [ $(whoami) == "root" ]; then
     echo "[ERR] => re-run installer without sudo privileges"
@@ -20,6 +20,7 @@ cat << "EOF"
         ██╔══██║   ██║   ██║     
         ██║  ██║   ██║   ███████╗
         ╚═╝  ╚═╝   ╚═╝   ╚══════╝
+
 EOF
 }
 
@@ -52,7 +53,7 @@ for i in "$@"; do
             echo "  -c|--configure"
             echo "      initializes the configuration process"
             echo
-            echo "  -p|--prefix=<path>"
+            echo "  -p=<path>|--prefix=<path>"
             echo "      specifies the installation path" 
             echo
             echo "  -h|--help"
@@ -72,16 +73,6 @@ for i in "$@"; do
 done
 # ARGS parser end
 
-if [ $COUNT -eq 0 ]; then
-    echo "[ERR] => No args detected, use --help for tips"
-    exit -1
-fi
-
-if [ $PREFIX -eq 0 ]; then
-    echo "[ERR] => No given path, quitting.."
-    exit -1
-fi
-
 signature
 
 # DIR selector
@@ -95,6 +86,16 @@ then
     then
         echo "A previous installation folder was found in $FIND, do you like override it? [y/n]"
         read response
+    else
+        if [ $PREFIX -eq 0 ]; then
+            echo "[ERR] => No installation folder found, no give path, run ./install -p=<path>.."
+            exit -1
+        fi
+    fi
+else 
+    if [ $PREFIX -eq 0 ]; then
+        echo "[ERR] => No installation folder found, no give path, run ./install -p=<path>.."
+        exit -1
     fi
 fi
 
@@ -185,6 +186,11 @@ if ! cp config "${FOLDER}bin"; then
     echo "An error occurred while copying config, exiting"
     exit -1
 fi
+
+if ! cp uninstall "${FOLDER}bin"; then
+    echo "An error occurred while copying uninstaller, exiting"
+    exit -1
+fi
 # DIRS & FILES checking/copying end
 
 # MAN 
@@ -267,11 +273,9 @@ else
 fi
 # man generation end
 
-echo "done"
-echo 
+echo "done."
 
 if [ $CONFIGURE -eq 1 ]; then
-    echo
     exec ./config --deps
 fi
 
